# Dependencies
markdown:         redcarpet
highlighter:      null

# Permalinks
permalink:        pretty

# Setup
title:            BlackDoc
tagline:          Black Theme for Jekyll
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              https://sstasl.github.io/eplan
baseurl:          /eplan

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.0

gems: ['jekyll-paginate']

github:
  repo:           https://github.com/karloespiritu/blackdoc
